site_name: SamplyCity
repo_url: "https://github.com/muratkendir/samplycity"
site_url: "https://muratkendir.github.io/samplycity"
nav:
  - Home: index.md
  - Building:
    - Buildings: building.md
    - "Building Subvariants": building_subvariants.md
  - Transportation: transportation.md
  - Vegetation: vegetation.md
  - Relief: relief.md
  - PointCloud: pointcloud.md
theme:
  name: material
  logo: ./images/logo.png
  favicon: ./images/favicon.png
  palette: 
  # Palette toggle for light mode
  - scheme: default
    primary: darkblue
    accent: cyan
    media: "(prefers-color-scheme: light)"
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  # Palette toggle for dark mode
  - scheme: slate
    primary: green
    accent: cyan
    media: "(prefers-color-scheme: dark)"
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - tables
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
