site_name: SamplyCity
nav:
  - Home: index.md
  - Building:
    - Buildings: building.md
    - "Building Subvariants": building_subvariants.md
  - Transportation: transportation.md
  - Vegetation: vegetation.md
  - Relief: relief.md
theme:
  name: material
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
